import type { CourseTool } from "@/features/learn/courses/types";

const ALL_QUESTION_SLUGS = [
  "balloon-pressure-temperature",
  "sealed-syringe-ideal-gas",
  "first-law-compression-sign",
  "engine-efficiency-limit",
  "two-charge-force-direction",
  "field-between-parallel-plates",
  "potential-vs-field-path",
  "capacitor-dielectric-energy",
  "current-from-charge-flow",
  "series-vs-parallel-brightness",
  "kirchhoff-loop-unknown",
  "rc-charging-time-constant",
  "field-around-bar-magnet",
  "charge-in-magnetic-field-path",
  "wire-force-right-hand",
  "loop-area-change-induced",
  "plane-mirror-image-distance",
  "concave-mirror-object-inside-f",
  "snell-air-to-water",
  "converging-lens-object-2f",
  "wave-speed-from-f-lambda",
  "doppler-ambulance-toward",
  "double-slit-path-difference",
  "thin-film-soap-constructive",
  "photon-energy-from-frequency",
  "photoelectric-threshold",
  "bohr-level-photon-emission",
  "fission-vs-fusion-mass-defect",
] as const;

const ALL_LESSON_SLUGS = [
  "kinetic-theory-and-ideal-gas",
  "first-law-entropy-and-heat-engines",
  "charge-force-and-electric-fields",
  "potential-energy-potential-and-capacitors",
  "current-resistance-and-simple-circuits",
  "kirchhoff-and-rc-circuits",
  "magnetic-fields-and-moving-charges",
  "induction-and-faraday",
  "reflection-and-mirror-images",
  "refraction-and-lens-images",
  "wave-properties-sound-and-doppler",
  "interference-diffraction-and-thin-films",
  "photons-photoelectric-and-spectra",
  "nuclear-decay-fission-and-fusion",
] as const;

export const tools: readonly CourseTool[] = [
  {
    kind: "practice",
    slug: "practice",
    title: "Practice",
    description:
      "Work every original AP Physics 2 item. Results stay on your account.",
    questionSlugs: [...ALL_QUESTION_SLUGS],
  },
  {
    kind: "quiz",
    slug: "quiz",
    title: "Quiz",
    description:
      "A short original check across gases, fields, circuits, and photons.",
    questionSlugs: [
      "balloon-pressure-temperature",
      "two-charge-force-direction",
      "current-from-charge-flow",
      "field-around-bar-magnet",
      "plane-mirror-image-distance",
      "wave-speed-from-f-lambda",
      "photon-energy-from-frequency",
    ],
  },
  {
    kind: "review",
    slug: "review",
    title: "Review",
    description: "Mixed original items from later in each unit.",
    questionSlugs: [
      "sealed-syringe-ideal-gas",
      "first-law-compression-sign",
      "field-between-parallel-plates",
      "potential-vs-field-path",
      "series-vs-parallel-brightness",
      "kirchhoff-loop-unknown",
      "charge-in-magnetic-field-path",
      "wire-force-right-hand",
      "concave-mirror-object-inside-f",
      "snell-air-to-water",
      "doppler-ambulance-toward",
      "double-slit-path-difference",
      "photoelectric-threshold",
      "bohr-level-photon-emission",
    ],
  },
  {
    kind: "notes",
    slug: "notes",
    title: "Notes",
    description: "Original lesson text for all seven AP Physics 2 units.",
    lessonSlugs: [...ALL_LESSON_SLUGS],
  },
  {
    kind: "readiness",
    slug: "readiness",
    title: "Readiness",
    description:
      "A mixed-difficulty original check. This is not a College Board exam.",
    questionSlugs: [
      "engine-efficiency-limit",
      "capacitor-dielectric-energy",
      "rc-charging-time-constant",
      "loop-area-change-induced",
      "converging-lens-object-2f",
      "thin-film-soap-constructive",
      "fission-vs-fusion-mass-defect",
      "kirchhoff-loop-unknown",
    ],
  },
];

export default tools;
